#!/bin/bash

rsync -zzPc misc/pip_pkg/dist/PYCLOAK-$(cat version)-py3-none-any.whl repo@projects.digithinkit.com:/repos/libs/ && rsync -zzPc version repo@projects.digithinkit.com:/repos/libs/PYCLOAK-latest.ver

